[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.13.0"
dependencies = [
    "basedpyright>=1.39.2",
    "datasets>=4.8.4",
    "huggingface-hub>=1.11.0",
    "jupyterlab-lsp>=5.3.0",
    "line-profiler>=5.0.2",
    "pandas>=3.0.2",
    "pyarrow>=23.0.1",
    "requests>=2.33.1",
    "transformers>=5.5.4",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.9.1",
  "torchvision>=0.24.1",
]
rocm = [
  "torch>=2.9.1",
  "torchvision>=0.24.1",
  "triton-rocm",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "rocm" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-rocm", extra = "rocm" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-rocm", extra = "rocm" },
]
triton-rocm= [
  { index = "pytorch-rocm", extra = "rocm" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
explicit = true
